general.import = ["~/.config/alacritty/themes/themes/oneiroi-melatonin.toml"]

[env]
# TERM = 'xterm-256-color'

[font]
size = 10
normal = { family = "JetBrainsMono Nerd font",style = "Regular" }
builtin_box_drawing = false

[window]
padding = {x = 10,y = 5}
dynamic_padding = true
decorations = "None"
opacity = 1
blur = true

[cursor.style]
blinking = "Always"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key= "Space", mods= "Control", chars= "\u0000" },
]
